### ISSUE TITLE
Is this project actively maintained ?

### ISSUE THREAD

**Issue by VincentFoulon80** [P1start/drawille-rs#12]
Hello @ftxqxd,

At first, sorry for the ping, I'm assuming you're quite busy so I'll make it short :
It's been a while since your last update on this repository, do you consider it still active ? If not, I'd suggest you to add another maintainer so this crate doesn't stay abandoned.
You can for example [add the Bus Factor +1 team to your crate](https://users.rust-lang.org/t/bus-factor-1-for-crates/17046) that'll eventually find another maintainer for this project. If you want, you can also add me, so I'll take care of this for you.

I don't want to see this great project being abandoned, that's why I'm contacting you today. 

Again, sorry for the inconvenience.
Sincerely,

**Comment by ftxqxd** [comment]
I haven't really had the time to maintain the project, so I'm happy to hand control over to someone else, as I don't really intend to work on it any more. I've added you as an owner on the crates.io repo; feel free to add anyone else who wants to contribute, too.

Thanks for your interest in the project – it's nice to know people are still using it, even if I did abandon it a while ago :)

**Comment by VincentFoulon80** [comment]
Thank you ! 🙇‍♂️
